### PR TITLE
added more changes to my file

### PR DESCRIPTION
**Pull request by tezcoding**
Added some changes

### CODE REVIEW

**Review by DianaSakayeva — COMMENTED** [review]
Looks good.

**Review by GUZELTURGANOVA — APPROVED** [review]
good job

**Review by Maira056 — APPROVED** [review]
hello

**Review by Gulnur1982 — CHANGES_REQUESTED** [review]
add more details

**Comment by tezcoding** [comment]
> good job

Thank you!

**Comment by tezcoding** [comment]
> hello

Hello there!

**Comment by tezcoding** [comment]
> add more details

@Gulnur1982  Thanks, added the requested changes

**Review by SergheiF — COMMENTED** [review]
great job

**Pull request merged**
